### ISSUE TITLE
copy text to clipboard

### ISSUE THREAD

**Issue by maguzzz** [maguzzz/Quotes#2]
A button next to the "next" button where you can copy the quote to the clipboard

**Comment by abitsalihu** [comment]
Hey @maguzzz, I would like to work on this issue. :)

**Comment by maguzzz** [comment]
> Hey @maguzzz, I would like to work on this issue. :)

Sure :D

**Comment by abitsalihu** [comment]
I will send the pr tomorrow at the latest. :)
